### PR TITLE
fix: add repo status failure call if commits fail quailty checks

### LINKED ISSUE #113: BUG: Missing update to Repo Status when commits fail Quality Checks
Post #111 , the GitHub check for `the-cla` never gets marked as passed or failed - see https://github.com/sonatype-nexus-community/community-handbook.sonatype.com/pull/28

Screenshot 2024-09-18 at 08 51 48

### PR DESCRIPTION
**Pull request by madpah**
Resolves #113

### CODE REVIEW

File: github/github.go [hunk 1]
```diff
@@ -366,6 +368,11 @@ func EvaluatePullRequest(logger *zap.Logger, postgres db.IClaDB, evalInfo *types
 			return err
 		}
 
+		err = createRepoStatus(client.Repositories, evalInfo.RepoOwner, evalInfo.RepoName, evalInfo.Sha, "failure", "One or more commits haven't met our Quality requirements.", botName)
```
Comment (bhamail) [inline github/github.go:371]: I'm looking into trying to use the Mock objects to see if we can assert some state in unit tests for these sorts of things. It might complicate this PR a little, but should hopefully open the door to better unit tests and maybe allow refactoring some of these huge methods into smaller units. Spoiler: `repositoriesMock` yadda, yadda...

**Review by bhamail — APPROVED** [review]
+1
